//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Score
    {
        public int Score__Id { get; set; }
        public string SubjectName { get; set; }
        public int StudentId { get; set; }
        public Nullable<decimal> Score { get; set; }
    
        public virtual Test_Student Test_Student { get; set; }
    }
}
